name: Static Analysis

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  check_duplicate_runs:
    name: Check for duplicate runs
    continue-on-error: true
    runs-on: ubuntu-20.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          concurrent_skipping: always
          cancel_others: true
          skip_after_successful_duplicate: true
          paths_ignore: '["**/README.md", "**/CHANGELOG.md", "**/LICENSE.txt"]'
          do_not_skip: '["pull_request"]'

  dialyzer:
    name: Static code analysis
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        elixir:
        - "1.16"
        otp:
        - "25.3"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Restore deps cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-{{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}

    - name: Restore _build cache
      uses: actions/cache@v2
      with:
        path: _build
        key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}

    - name: Install hex
      run: mix local.hex --force

    - name: Install rebar
      run: mix local.rebar --force

    - name: Install package dependencies
      run: mix deps.get

    - name: Compile package dependencies
      run: mix deps.compile

    - name: Restore PLT cache
      id: plt_cache
      uses: actions/cache@v2
      with:
        path: priv/plts
        key: plt-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          plt-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          plt-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

    - name: Create PLTs
      if: steps.plt_cache.outputs.cache-hit != 'true'
      run: mix dialyzer --plt

    # By default, the GitHub Cache action will only save the cache if all steps in the job succeed,
    # so we separate the cache restore and save steps in case running dialyzer fails.
    - name: Save PLT cache
      id: plt_cache_save
      uses: actions/cache/save@v3
      if: steps.plt_cache.outputs.cache-hit != 'true'
      with:
        key: plt-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        path: priv/plts

    - name: Run dialyzer
      run: mix dialyzer --format github
